#!/usr/bin/env bash
# ==============================================================================
# Core Module: Toolchain, Paru & System Packages Installation
# ==============================================================================

set -euo pipefail

build_paru_helper() {
    log_step "STEP 1: Dependencies & Native AUR Helper Build (paru)"

    log_info "Synchronizing package databases via pacman -Sy..."
    sudo pacman -Sy

    # Enable native Color and VerbosePkgLists in /etc/pacman.conf so pacman and paru render cleanly
    log_info "Enabling native Color and VerbosePkgLists in /etc/pacman.conf..."
    sudo sed -i 's/^#Color/Color/' /etc/pacman.conf
    sudo sed -i 's/^#VerbosePkgLists/VerbosePkgLists/' /etc/pacman.conf

    log_info "Installing prerequisite build toolchain via pacman..."
    sudo pacman -S --needed --noconfirm base-devel git rust bat

    if command -v paru &>/dev/null; then
        log_success "paru is already installed at $(command -v paru). Skipping build."
    else
        log_info "Building paru from source using secure temporary directory as non-root user..."
        local paru_build_dir
        paru_build_dir=$(mktemp -d -p /tmp paru-build-XXXXXX)
        CLEANUP_PATHS+=("$paru_build_dir")

        git clone --depth 1 https://aur.archlinux.org/paru.git "${paru_build_dir}/paru"
        (
            cd "${paru_build_dir}/paru"
            makepkg -si --noconfirm
        )
        rm -rf "$paru_build_dir"
        log_success "paru successfully compiled and installed."
    fi

    log_info "Configuring ~/.config/paru/paru.conf..."
    mkdir -p "${HOME}/.config/paru"
    cat > "${HOME}/.config/paru/paru.conf" << 'EOF'
# Generated by automated post-install setup
[options]
BottomUp
SudoLoop
EOF
    log_success "paru configuration deployed."
}

install_system_packages() {
    log_step "STEP 4: Package Installation & Default Shell Setup"

    local system_packages=(
        # Compositor & Display
        wayfire
        xorg-xwayland
        greetd
        greetd-regreet

        # Session Locking & Auth
        hyprlock
        swayidle
        hyprpaper
        hyprpolkitagent

        # Portals & Streaming
        pipewire
        wireplumber
        xdg-desktop-portal
        xdg-desktop-portal-wlr
        xdg-desktop-portal-gtk

        # UI & Utilities
        waybar
        fuzzel
        mako
        wlogout
        yad
        kanshi
        networkmanager
        network-manager-applet
        bluez
        bluez-utils
        blueman
        libnotify
        kdeconnect
        sshfs

        # GTK Schemas & Integration
        gtk3
        gtk4
        gsettings-desktop-schemas

        # Terminals & Shell
        foot
        alacritty
        fish
        starship

        # Fonts & Icons
        ttf-jetbrains-mono-nerd
        noto-fonts
        noto-fonts-emoji
        papirus-icon-theme

        # Applications & Media
        geany
        vlc
        qt6-wayland
        imv
        mpd
        mpc
        playerctl
        pulsemixer
        brightnessctl
        wl-clipboard

        # File Manager
        thunar
        tumbler
        thunar-archive-plugin
        file-roller

        # Screen Capture & Color
        grim
        slurp
        wf-recorder
        pastel
        imagemagick
    )

    log_info "Installing core package stack via paru..."
    if ! paru -S --needed --noconfirm "${system_packages[@]}"; then
        log_warn "Bulk package installation encountered an error. Retrying with individual package fallback..."
        for pkg in "${system_packages[@]}"; do
            paru -S --needed --noconfirm "$pkg" || log_warn "Failed to install optional package: $pkg (skipping)"
        done
    fi

    log_info "Configuring default user shell to fish..."
    local fish_bin
    fish_bin=$(command -v fish || echo "/usr/bin/fish")
    if ! grep -qxF "$fish_bin" /etc/shells; then
        echo "$fish_bin" | sudo tee -a /etc/shells >/dev/null
    fi
    sudo chsh -s "$fish_bin" "$USER"

    log_success "Core package stack and shell configuration complete."
}
