#!/usr/bin/env bash
# ==============================================================================
# Core Module: Toolchain, Paru & System Packages Installation
# ==============================================================================

set -euo pipefail

build_paru_helper() {
    log_step "STEP 1: Dependencies & Native AUR Helper Build (paru)"

    log_info "Synchronizing package databases via pacman -Sy..."
    sudo pacman -Sy

    # Enable native Color, VerbosePkgLists and DisableDownloadTimeout in /etc/pacman.conf
    log_info "Enabling native Color, VerbosePkgLists and DisableDownloadTimeout in /etc/pacman.conf..."
    sudo sed -i 's/^#Color/Color/' /etc/pacman.conf 2>/dev/null || true
    sudo sed -i 's/^#VerbosePkgLists/VerbosePkgLists/' /etc/pacman.conf 2>/dev/null || true
    sudo sed -i 's/^#DisableDownloadTimeout/DisableDownloadTimeout/' /etc/pacman.conf 2>/dev/null || true
    if ! grep -q "^DisableDownloadTimeout" /etc/pacman.conf 2>/dev/null; then
        sudo sed -i '/^ParallelDownloads/a DisableDownloadTimeout' /etc/pacman.conf 2>/dev/null || true
    fi

    log_info "Installing prerequisite build toolchain via pacman..."
    sudo pacman -S --needed --noconfirm base-devel git rust bat

    if command -v paru &>/dev/null; then
        log_success "paru is already installed at $(command -v paru). Skipping build."
    else
        log_info "Building paru from source using secure temporary directory as non-root user..."
        local paru_build_dir
        paru_build_dir=$(mktemp -d -p /tmp paru-build-XXXXXX)
        CLEANUP_PATHS+=("$paru_build_dir")

        git clone --depth 1 https://aur.archlinux.org/paru.git "${paru_build_dir}/paru"
        (
            cd "${paru_build_dir}/paru"
            makepkg -si --noconfirm
        )
        rm -rf "$paru_build_dir"
        log_success "paru successfully compiled and installed."
    fi

    log_info "Configuring ~/.config/paru/paru.conf..."
    mkdir -p "${HOME}/.config/paru"
    cat > "${HOME}/.config/paru/paru.conf" << 'EOF'
# Generated by automated post-install setup
[options]
BottomUp
SudoLoop
EOF
    log_success "paru configuration deployed."
}

# ------------------------------------------------------------------------------
# Conflicting Package Audit & Hygiene Subsystem
# ------------------------------------------------------------------------------
audit_conflicting_packages() {
    log_step "STEP: Package Conflict Detection & Hygiene Audit"
    log_info "Auditing system for packages that conflict with the Wayfire desktop suite..."

    # Candidate conflicting / redundant packages across core desktop categories
    local -a candidate_conflicts=(
        # File Managers (conflicts with Nautilus / PCManFM-Qt desktop stack)
        thunar
        thunar-volman
        thunar-archive-plugin
        tumbler
        dolphin
        nemo
        caja
        pcmanfm             # Legacy GTK version (we bundle pcmanfm-qt)

        # Screen Capture (conflicts with Grim/Slurp/Swappy Wayland stack)
        spectacle
        flameshot
        ksnip

        # Notification Daemons (conflicts with Mako; multiple daemons cause D-Bus clashes)
        dunst
        fnott
        swaync
        xfce4-notifyd

        # Screen Lockers (conflicts with Hyprlock)
        swaylock
        swaylock-effects
        i3lock

        # Redundant/Conflicting Polkit Agents
        polkit-kde-agent
        lxsession
        lxqt-policykit

        # Redundant / Legacy App Launchers (conflicts with bundled rofi-wayland)
        wofi
        fuzzel
        tofi
        dmenu

        # Legacy Desktop Panels (conflicts with Waybar)
        tint2
        polybar
        xfce4-panel

        # Conflicting / Unreadable Fancy Calligraphy Fonts (superseded by clean Noto Sans Arabic)
        ttf-scheherazade-new

        # Legacy / Conflicting Display Managers (superseded by modern SDDM)
        greetd
        greetd-regreet
        lightdm
        lightdm-gtk-greeter
        gdm
        lxdm
    )

    # Protected whitelist: apps bundled by this setup that MUST NOT be removed
    local -a bundled_whitelist=(
        nautilus
        gvfs
        gvfs-mtp
        gvfs-smb
        file-roller
        sushi
        pcmanfm-qt
        rofi-wayland
        nwg-menu
        waybar
        mako
        hyprlock
        swayidle
        swappy
        grim
        slurp
        copyq
        cliphist
        wl-clipboard
        foot
        alacritty
        wayfire
        wf-shell
        wcm
        xsettingsd
        sddm
    )

    local -a detected_conflicts=()
    for pkg in "${candidate_conflicts[@]}"; do
        if pacman -Qq "$pkg" &>/dev/null; then
            # Verify the package is NOT in the whitelist (safety invariant)
            local is_whitelisted=0
            for safe_pkg in "${bundled_whitelist[@]}"; do
                if [[ "$pkg" == "$safe_pkg" ]]; then
                    is_whitelisted=1
                    break
                fi
            done
            if [[ $is_whitelisted -eq 0 ]]; then
                detected_conflicts+=("$pkg")
            fi
        fi
    done

    if (( ${#detected_conflicts[@]} == 0 )); then
        log_success "No conflicting packages detected on the system. Package hygiene verified."
        return 0
    fi

    log_warn "Detected ${#detected_conflicts[@]} conflicting/redundant package(s) on the system:"
    for pkg in "${detected_conflicts[@]}"; do
        printf "  - ${COLOR_RED}%s${COLOR_RESET}\n" "$pkg"
    done

    local proceed="y"
    if [[ -t 0 ]]; then
        printf "\n"
        read -rp "Would you like to remove these conflicting packages while keeping all bundled apps? [Y/n]: " choice
        proceed="${choice:-y}"
    fi

    case "${proceed,,}" in
        y|yes)
            log_info "Removing conflicting packages safely via pacman -Rns..."
            sudo pacman -Rns --noconfirm "${detected_conflicts[@]}" 2>/dev/null || {
                log_warn "Some packages had reverse dependencies. Attempting removal without cascading..."
                sudo pacman -R --noconfirm "${detected_conflicts[@]}" || log_warn "Manual review may be required for some packages."
            }
            log_success "Conflicting packages successfully removed. Bundled stack preserved."
            ;;
        *)
            log_info "Skipping conflicting package removal at user request."
            ;;
    esac
}

install_system_packages() {
    log_step "STEP 5: Package Installation & Default Shell Setup"

    # Sanitize paru.conf before any operations to eliminate unknown option errors
    if [[ -f "${HOME}/.config/paru/paru.conf" ]]; then
        sed -i '/^[[:space:]]*Color/d' "${HOME}/.config/paru/paru.conf" 2>/dev/null || true
        sed -i '/^[[:space:]]*FileManager/d' "${HOME}/.config/paru/paru.conf" 2>/dev/null || true
    fi

    # Ensure pacman download resilience and prevent slow-speed aborts on large downloads
    log_info "Configuring pacman download resilience (DisableDownloadTimeout) in /etc/pacman.conf..."
    sudo sed -i 's/^#DisableDownloadTimeout/DisableDownloadTimeout/' /etc/pacman.conf 2>/dev/null || true
    if ! grep -q "^DisableDownloadTimeout" /etc/pacman.conf 2>/dev/null; then
        sudo sed -i '/^ParallelDownloads/a DisableDownloadTimeout' /etc/pacman.conf 2>/dev/null || true
    fi

    # Fix IPv6 unexpected EOF connection drops (prefer IPv4 for reliable AUR & mirrors)
    if [[ -f /etc/gai.conf ]]; then
        sudo sed -i 's/^#precedence ::ffff:0:0\/96  100/precedence ::ffff:0:0\/96  100/' /etc/gai.conf 2>/dev/null || true
    fi

    # Optimize ALHP mirrorlist priority to use fast Cloudflare edge and disable failing cdn.alhp.dev
    if [[ -f /etc/pacman.d/alhp-mirrorlist ]]; then
        log_info "Prioritizing Cloudflare CDN mirror and disabling failing cdn.alhp.dev in /etc/pacman.d/alhp-mirrorlist..."
        sudo sed -i 's|^Server = https://cdn.alhp.dev|#Server = https://cdn.alhp.dev|' /etc/pacman.d/alhp-mirrorlist 2>/dev/null || true
        sudo sed -i '/krautflare/d' /etc/pacman.d/alhp-mirrorlist 2>/dev/null || true
        sudo sed -i '1i Server = https://alhp.krautflare.de/$repo/os/$arch/' /etc/pacman.d/alhp-mirrorlist 2>/dev/null || true
    fi

    # 1. Official Arch Repository Packages (Installed directly via pacman for maximum speed and reliability)
    local official_packages=(
        # Compositor, Desktop Management & Tools
        wayfire
        wf-shell
        wcm
        xsettingsd
        xorg-xwayland
        sddm
        qt6-svg
        qt6-virtualkeyboard
        qt6-multimedia-ffmpeg

        # Session Locking & Auth
        hyprlock
        swayidle
        hyprpaper
        hyprpolkitagent

        # Portals, XDG & Streaming
        pipewire
        wireplumber
        xdg-desktop-portal
        xdg-desktop-portal-wlr
        xdg-desktop-portal-gtk
        xdg-user-dirs
        totem-pl-parser
        tevent

        # UI, Launchers & Utilities
        waybar
        rofi-wayland
        nwg-menu
        mako
        yad
        kanshi
        copyq
        cliphist
        wl-clipboard
        wtype
        networkmanager
        network-manager-applet
        bluez
        bluez-utils
        blueman
        libnotify
        kdeconnect
        sshfs

        # GTK Schemas & Qt Theming Integration
        gtk3
        gtk4
        gsettings-desktop-schemas
        qt5ct
        qt6ct
        kvantum

        # Terminals & Shell
        foot
        alacritty
        fish
        starship

        # Fonts & Icons (including modern clean Arabic typography: Noto Sans Arabic)
        ttf-jetbrains-mono-nerd
        noto-fonts
        noto-fonts-emoji
        noto-fonts-extra
        papirus-icon-theme

        # Applications & Media
        geany
        vlc
        qt6-wayland
        qt6-multimedia-ffmpeg
        imv
        mpd
        mpc
        playerctl
        pulsemixer
        pavucontrol
        brightnessctl

        # File Manager & Desktop Surface (GNOME Files + PCManFM-Qt for Desktop Menu)
        nautilus
        gvfs
        gvfs-mtp
        gvfs-smb
        file-roller
        sushi
        pcmanfm-qt

        # Screen Capture & Color (Grim + Slurp + Swappy annotation)
        grim
        slurp
        swappy
        wf-recorder
        pastel
        imagemagick
    )

    log_info "Installing official repository packages via pacman..."
    sudo pacman -S --needed --noconfirm "${official_packages[@]}"
    log_success "Official package stack successfully installed."

    # 2. AUR Packages (wlogout with GPG key pre-import and --skippgpcheck fallback)
    if ! command -v wlogout &>/dev/null; then
        log_info "Installing wlogout from AUR..."
        # Import ArtsyMacaw's public signing key (E25D679AF73C6D2F) to prevent makepkg signature verification aborts
        gpg --recv-keys E25D679AF73C6D2F 2>/dev/null || \
            gpg --keyserver keyserver.ubuntu.com --recv-keys E25D679AF73C6D2F 2>/dev/null || \
            gpg --keyserver hkps://keys.openpgp.org --recv-keys E25D679AF73C6D2F 2>/dev/null || true

        if ! paru -S --needed --noconfirm --mflags "--skippgpcheck" wlogout 2>/dev/null; then
            log_warn "Standard paru install failed for wlogout. Attempting manual build with --skippgpcheck..."
            local wl_dir
            wl_dir=$(mktemp -d -p /tmp wlogout-build-XXXXXX)
            CLEANUP_PATHS+=("$wl_dir")
            if git clone --depth 1 https://aur.archlinux.org/wlogout.git "${wl_dir}/wlogout" 2>/dev/null; then
                (
                    cd "${wl_dir}/wlogout"
                    makepkg -si --noconfirm --skippgpcheck
                ) || log_warn "wlogout manual build failed; fuzzel/rofi power menu overlay will be used as fallback."
            fi
            rm -rf "$wl_dir" 2>/dev/null || true
        fi

        if command -v wlogout &>/dev/null; then
            log_success "wlogout installed successfully."
        else
            log_info "wlogout not installed; rofi power menu overlay is active as fallback."
        fi
    fi

    # Install Bibata Cursor Theme from AUR if not already installed
    if ! pacman -Qq bibata-cursor-theme-bin &>/dev/null && ! pacman -Qq bibata-cursor-theme &>/dev/null; then
        log_info "Installing Bibata cursor theme (bibata-cursor-theme-bin) from AUR..."
        if command -v paru &>/dev/null; then
            paru -S --needed --noconfirm bibata-cursor-theme-bin 2>/dev/null || \
            paru -S --needed --noconfirm bibata-cursor-theme 2>/dev/null || true
        fi
    fi

    # 3. Default Shell Setup
    log_info "Configuring default user shell to fish..."
    local fish_bin
    fish_bin=$(command -v fish || echo "/usr/bin/fish")
    if ! grep -qxF "$fish_bin" /etc/shells; then
        echo "$fish_bin" | sudo tee -a /etc/shells >/dev/null
    fi
    local current_user_shell
    current_user_shell=$(getent passwd "$USER" | cut -d: -f7)
    if [[ "$current_user_shell" != "$fish_bin" ]]; then
        sudo chsh -s "$fish_bin" "$USER"
    fi

    log_success "Core package stack and shell configuration complete."
}
