#!/usr/bin/env bash
# ==============================================================================
# Core Module: Toolchain, Paru & System Packages Installation
# ==============================================================================

set -euo pipefail

build_paru_helper() {
    log_step "STEP 1: Dependencies & Native AUR Helper Build (paru)"

    log_info "Synchronizing package databases via pacman -Sy..."
    sudo pacman -Sy

    # Enable native Color and VerbosePkgLists in /etc/pacman.conf so pacman and paru render cleanly
    log_info "Enabling native Color and VerbosePkgLists in /etc/pacman.conf..."
    sudo sed -i 's/^#Color/Color/' /etc/pacman.conf
    sudo sed -i 's/^#VerbosePkgLists/VerbosePkgLists/' /etc/pacman.conf

    log_info "Installing prerequisite build toolchain via pacman..."
    sudo pacman -S --needed --noconfirm base-devel git rust bat

    if command -v paru &>/dev/null; then
        log_success "paru is already installed at $(command -v paru). Skipping build."
    else
        log_info "Building paru from source using secure temporary directory as non-root user..."
        local paru_build_dir
        paru_build_dir=$(mktemp -d -p /tmp paru-build-XXXXXX)
        CLEANUP_PATHS+=("$paru_build_dir")

        git clone --depth 1 https://aur.archlinux.org/paru.git "${paru_build_dir}/paru"
        (
            cd "${paru_build_dir}/paru"
            makepkg -si --noconfirm
        )
        rm -rf "$paru_build_dir"
        log_success "paru successfully compiled and installed."
    fi

    log_info "Configuring ~/.config/paru/paru.conf..."
    mkdir -p "${HOME}/.config/paru"
    cat > "${HOME}/.config/paru/paru.conf" << 'EOF'
# Generated by automated post-install setup
[options]
BottomUp
SudoLoop
EOF
    log_success "paru configuration deployed."
}

install_system_packages() {
    log_step "STEP 4: Package Installation & Default Shell Setup"

    # Sanitize paru.conf before any operations to eliminate unknown option errors
    if [[ -f "${HOME}/.config/paru/paru.conf" ]]; then
        sed -i '/^[[:space:]]*Color/d' "${HOME}/.config/paru/paru.conf" 2>/dev/null || true
        sed -i '/^[[:space:]]*FileManager/d' "${HOME}/.config/paru/paru.conf" 2>/dev/null || true
    fi

    # 1. Official Arch Repository Packages (Installed directly via pacman for maximum speed and reliability)
    local official_packages=(
        # Compositor & Display
        wayfire
        wf-shell
        xorg-xwayland
        greetd
        greetd-regreet

        # Session Locking & Auth
        hyprlock
        swayidle
        hyprpaper
        hyprpolkitagent

        # Portals, XDG & Streaming
        pipewire
        wireplumber
        xdg-desktop-portal
        xdg-desktop-portal-wlr
        xdg-desktop-portal-gtk
        xdg-user-dirs

        # UI, Launchers & Utilities
        waybar
        rofi-wayland
        wofi
        fuzzel
        mako
        yad
        kanshi
        cliphist
        networkmanager
        network-manager-applet
        bluez
        bluez-utils
        blueman
        libnotify
        kdeconnect
        sshfs

        # GTK Schemas & Qt Theming Integration
        gtk3
        gtk4
        gsettings-desktop-schemas
        qt5ct
        qt6ct
        kvantum

        # Terminals & Shell
        foot
        alacritty
        fish
        starship

        # Fonts & Icons
        ttf-jetbrains-mono-nerd
        noto-fonts
        noto-fonts-emoji
        papirus-icon-theme

        # Applications & Media
        geany
        vlc
        qt6-wayland
        qt6-multimedia-ffmpeg
        imv
        mpd
        mpc
        playerctl
        pulsemixer
        pavucontrol
        brightnessctl
        wl-clipboard

        # File Manager
        thunar
        tumbler
        thunar-archive-plugin
        file-roller

        # Screen Capture & Color
        spectacle
        grim
        slurp
        wf-recorder
        pastel
        imagemagick
    )

    log_info "Installing official repository packages via pacman..."
    sudo pacman -S --needed --noconfirm "${official_packages[@]}"
    log_success "Official package stack successfully installed."

    # 2. AUR Packages (wlogout with GPG key pre-import and --skippgpcheck fallback)
    if ! command -v wlogout &>/dev/null; then
        log_info "Installing wlogout from AUR..."
        # Import ArtsyMacaw's public signing key (E25D679AF73C6D2F) to prevent makepkg signature verification aborts
        gpg --recv-keys E25D679AF73C6D2F 2>/dev/null || \
            gpg --keyserver keyserver.ubuntu.com --recv-keys E25D679AF73C6D2F 2>/dev/null || \
            gpg --keyserver hkps://keys.openpgp.org --recv-keys E25D679AF73C6D2F 2>/dev/null || true

        if ! paru -S --needed --noconfirm --mflags "--skippgpcheck" wlogout 2>/dev/null; then
            log_warn "Standard paru install failed for wlogout. Attempting manual build with --skippgpcheck..."
            local wl_dir
            wl_dir=$(mktemp -d -p /tmp wlogout-build-XXXXXX)
            CLEANUP_PATHS+=("$wl_dir")
            if git clone --depth 1 https://aur.archlinux.org/wlogout.git "${wl_dir}/wlogout" 2>/dev/null; then
                (
                    cd "${wl_dir}/wlogout"
                    makepkg -si --noconfirm --skippgpcheck
                ) || log_warn "wlogout manual build failed; fuzzel/rofi power menu overlay will be used as fallback."
            fi
            rm -rf "$wl_dir" 2>/dev/null || true
        fi

        if command -v wlogout &>/dev/null; then
            log_success "wlogout installed successfully."
        else
            log_info "wlogout not installed; fuzzel/rofi power menu overlay is active as fallback."
        fi
    fi

    # 3. Default Shell Setup
    log_info "Configuring default user shell to fish..."
    local fish_bin
    fish_bin=$(command -v fish || echo "/usr/bin/fish")
    if ! grep -qxF "$fish_bin" /etc/shells; then
        echo "$fish_bin" | sudo tee -a /etc/shells >/dev/null
    fi
    local current_user_shell
    current_user_shell=$(getent passwd "$USER" | cut -d: -f7)
    if [[ "$current_user_shell" != "$fish_bin" ]]; then
        sudo chsh -s "$fish_bin" "$USER"
    fi

    log_success "Core package stack and shell configuration complete."
}
